# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_XOR_IP_0_0/design_1_XOR_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_XOR_IP_0_0 || ORIG_REF_NAME==design_1_XOR_IP_0_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: C:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_XOR_IP_0_0/design_1_XOR_IP_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_XOR_IP_0_0 || ORIG_REF_NAME==design_1_XOR_IP_0_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: C:/Users/Blaz/Desktop/UPLOAD/NEURAL_NETWORK_XOR_CPU/NEURAL_NETWORK_XOR_CPU.srcs/sources_1/bd/design_1/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1'. Do not add the DONT_TOUCH constraint.
